version: 0.2

env:
  variables:
    TEST_VAR: "Hello"
phases:
  build:
    commands:
      - echo "Installing Go..."
      # Make sure goenv is up to date
      - cd $HOME/.goenv && git pull --ff-only && cd -
      # Install Go 1.17
      - goenv install 1.21
      - goenv global 1.21
      - echo "Running build..."
      - echo "Running deploy..."