version: 0.2

env:
  variables:
    TEST_VAR: "Hello"
  secrets-manager:
    DB_USERNAME: "arn:aws:secretsmanager:us-east-1:992382528358:secret:rds!cluster-adc64676-287a-4c8b-8936-1d7b03978209-t0TdFi:username"
    DB_PASSWORD: "arn:aws:secretsmanager:us-east-1:992382528358:secret:rds!cluster-adc64676-287a-4c8b-8936-1d7b03978209-t0TdFi:password"

phases:
  build:
    commands:
      # Need to use EC2-based CodeBuild instead of lambda, since Lambda CodeBuild doesn't support VPC's, which we need for DB access
      # Install Go since EC2-based CodeBuild Docker images don't have it
      - echo "Installing Postgres Client..."
      - sudo dnf -y install postgresql15.x86_64
      - echo "Installing Go..."
      - cd $HOME/.goenv && git pull --ff-only && cd -
      - goenv install 1.21.7
      - goenv global 1.21.7
      - echo "Connect to DB..."
      - export PGPASSWORD=$DB_PASSWORD
      - psql --host=assets-2-instance-1.c52ac2emar8b.us-east-1.rds.amazonaws.com --port=5432 --dbname=postgres --username="$DB_USERNAME" -c "SELECT * FROM reports.cloud_formation_templates"
      - echo "Running deploy..."